name: frontend deployment
# Trigger workflow when code is pushed
on:

  # Run deployment only when pushing to mentioned branch
  push:
    branches:
      - main

# Prevent multiple deployments running simultaneously
concurrency:

  # Unique concurrency group name
  group: production-frontend

  # Cancel older running deployment if new push comes
  cancel-in-progress: true

# Jobs section
jobs:

  # Deployment job
  deploy:

    # GitHub creates Ubuntu Linux runner
    runs-on: ubuntu-latest

    # Stop workflow if running too long
    timeout-minutes: 30


    # Workflow steps
    steps:

      # Download repository code from GitHub
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Install Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4

        with:

          # Node.js version used for Angular build
          node-version: 20

          # Cache npm dependencies for faster builds
          cache: npm
          cache-dependency-path: package-lock.json
 

      # Install project dependencies
      - name: Install Dependencies

        # npm ci installs exact versions from package-lock.json
        run: npm ci


      # Run Angular lint validation
    # - name: Run Lint Check

        # Checks coding issues and bad patterns
     #  run: npm run lint


      # Run frontend unit tests
    # - name: Run Unit Tests

        # Run tests in headless Chrome browser
      # run: npm test -- --watch=false --browsers=ChromeHeadless


      # Check vulnerable npm packages
      - name: Run Security Audit

        # Fail deployment if high severity vulnerabilities found
        run: |
          npm audit --audit-level=high || true

      - name: Verify Environment
        run: |
          echo "Production build started"
 
      # Build Angular production application
      - name: Build Angular Production App
        run: ng build --configuration production

      # Verify build output exists
      - name: Verify Build Output
        run: |

          # Check if build folder exists
          if [ ! -d "dist/ai-interview-app/browser" ]; then
            echo "Build folder missing!"
            exit 1
          fi

          # Check if index.html exists
          if [ ! -f "dist/ai-interview-app/browser/index.html" ]; then
            echo "index.html missing!"
            exit 1
          fi

      # Authenticate GitHub Actions with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:

          # AWS IAM Access Key
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          # AWS IAM Secret Key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          # AWS region
          aws-region: ${{ secrets.AWS_REGION }}


      # Backup current production index.html
      - name: Backup Current index.html
        run: |

          # Copy current live index.html into rollback folder
          aws s3 cp \
          s3://${{ secrets.S3_BUCKET_NAME }}/index.html \
          s3://${{ secrets.S3_BUCKET_NAME }}/rollback/index-$(date +%Y%m%d-%H%M%S).html || true


      # Upload static frontend assets
      - name: Upload Static Assets
        run: |
          aws s3 sync dist/ai-interview-app/browser s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable"


      # Upload index.html separately
      - name: Upload index.html
        run: |

          # Upload latest index.html
          aws s3 cp dist/ai-interview-app/browser/index.html \
          s3://${{ secrets.S3_BUCKET_NAME }}/index.html \
          --cache-control "no-cache,no-store,must-revalidate"  # Prevent browser caching old HTML


      # Verify uploaded S3 files
      - name: Verify Uploaded Files
        run: |

          # List uploaded bucket files
          aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}


      # Clear CloudFront cache
      - name: Invalidate CloudFront Cache
        run: |

          # Create CloudFront invalidation
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html" "/" # Invalidate homepage and index.html


      # Validate deployed frontend is reachable
     # Validate deployed frontend is reachable

      - name: Deployment Health Check
        run: |
          set -e
          URL="https://${{ secrets.DOMAIN_NAME }}"
          echo "Checking URL: $URL"
          sleep 60
          for i in {1..5}; do
            echo "Attempt $i"
            if curl -L --fail --silent --show-error "$URL" > /dev/null; then
              echo "Deployment health check passed!"
              exit 0
            fi
            echo "Health check failed. Retrying in 15 seconds..."
            sleep 15
          done
          echo "Deployment health check failed after multiple attempts!"
          exit 1
 
      # Final success message
      - name: Deployment Success
        run: |
          echo " frontend deployed successfully!"