name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 1. Get code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Download model
      run: |
        python download_model.py

    # 5. Run tests
    - name: Run tests
      run: |
        pytest -v
    