name: Stress Level Prediction

on:
    push:
        branches: ["main", "temp"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: Install dependencies
              run: |
                pip install -r requirements.txt
            - name: Run tests
              run: |
               pytest -v
            # 2. Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

             # 3. Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            # 4. Build and Push Docker image
            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/stress-app:latest
            - name: Deploy to EC2 (Blue-Green)
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                  IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/stress-app:latest

                  echo "Pull latest image"
                  docker pull $IMAGE

                  echo "Check current running container"
                  if docker ps --format '{{.Names}}' | grep -q stress-blue; then

                      CURRENT=blue
                      NEW=green
                      NEW_PORT=8053
                      OLD_PORT=8052
                  else
                      CURRENT=green
                      NEW=blue
                      NEW_PORT=8052
                      OLD_PORT=8053
                  fi

                  echo "Running new version on $NEW ($NEW_PORT)"

                  docker stop stress-$NEW || true
                  docker rm stress-$NEW || true

                  docker run -d -p $NEW_PORT:8501 --name stress-$NEW $IMAGE

                  echo "Waiting for app to start..."
                  sleep 10

                  echo "Health check..."
                  curl -f http://localhost:$NEW_PORT || exit 1

                  echo "Stopping old version ($CURRENT)"
                  docker stop stress-$CURRENT || true
                  docker rm stress-$CURRENT || true

                  echo "Switch complete!"