name: Deploy Stress Level Prediction Backend (Blue-Green Dev)

on:
  push:
    branches: ["main","temp"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: docker build --no-cache -t challanaveen409/health:${{ github.sha }} .

      # 3. Security scan using Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: challanaveen409/health:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL
      # 4. Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      # 5. Push Docker image
      - name: Push Docker image
        run: docker push challanaveen409/health:${{ github.sha }}
      # 6. Deploy to EC2 (Blue-Green)
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            IMAGE_TAG=${{ github.sha }}
            NGINX_CONF="/etc/nginx/sites-available/health.conf"conf"
            
            
            echo "Pulling latest image..." 
            docker pull challanaveen409/health:$IMAGE_TAG

            echo "Detecting active port..." 
            ACTIVE_PORT=$(grep -E "server 127.0.0.1:[0-9]+" $NGINX_CONF | grep -v down | grep -oP '127\.0\.0\.1:\K[0-9]+' | head -1)

            if [ "$ACTIVE_PORT" = "8003" ]; then 
              NEW_PORT=8004 
              ACTIVE_COLOR="blue" 
              NEW_COLOR="green" 
            else 
              NEW_PORT=8003 
              ACTIVE_COLOR="green" 
              NEW_COLOR="blue" 
            fi
            echo "Active: $ACTIVE_COLOR ($ACTIVE_PORT)" 
            echo "Deploying: $NEW_COLOR ($NEW_PORT)" 

            docker stop health-$NEW_COLOR || true 
            docker rm health-$NEW_COLOR || true

            echo "Starting new container..." 
            docker run -d \ 
              --restart unless-stopped \ 
              --name health-$NEW_COLOR \ 
              -p $NEW_PORT:8501 \ 
              challanaveen409/health:$IMAGE_TAG

              echo "Waiting for app..." 
              sleep 15
            
              echo "Health check..." 
              if ! curl -f http://localhost:$NEW_PORT; then 
                echo "Health check failed!" 
                docker stop health-$NEW_COLOR 
                docker rm health-$NEW_COLOR 
                exit 1 
              fi

              echo "Switching traffic..." 
              sudo sed -i "s/server 127.0.0.1:$NEW_PORT .*down;/server 127.0.0.1:$NEW_PORT weight=100;/" $NGINX_CONF 
              sudo sed -i "s/server 127.0.0.1:$ACTIVE_PORT .*;/server 127.0.0.1:$ACTIVE_PORT down;/" $NGINX_CONF 
              sudo nginx -t 
              sudo systemctl reload nginx

              echo "Stopping old container..." 
              docker stop health-$ACTIVE_COLOR 
              docker rm health-$ACTIVE_COLOR

              echo "Deployment successful!"